name: Build Image nginx-non-root

on:
  push:
    branches:
      - main
    tags:
      - "*"
  schedule:
    - cron: "15 4 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            mtr.devops.telekom.de/mcsps/nginx-non-root
            ghcr.io/mcsps/nginx-non-root
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v2.4.0"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to MTR
        uses: docker/login-action@v3
        with:
          registry: mtr.devops.telekom.de
          username: ${{ secrets.MTR_USERNAME }}
          password: ${{ secrets.MTR_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-push
        with:
          context: ./nginx-non-root
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mtr.devops.telekom.de/mcsps/nginx-non-root:latest
            ghcr.io/mcsps/nginx-non-root:latest
            ${{ steps.meta.outputs.tags }}
      - name: Sign Push
        run: |
          cosign sign --key env://COSIGN_KEY --tlog-upload=false mtr.devops.telekom.de/mcsps/nginx-non-root@${{ steps.build-push.outputs.digest }}
          cosign sign --key env://COSIGN_KEY --tlog-upload=false ghcr.io/mcsps/nginx-non-root@${{ steps.build-push.outputs.digest }}
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
